# Generated by Django 4.1.2 on 2023-04-18 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=3, verbose_name='Номер взводу')),
                ('strength', models.CharField(max_length=2, verbose_name='Чисельність взводу')),
                ('external_id', models.PositiveIntegerField(verbose_name='Chat id')),
            ],
            options={
                'verbose_name': 'Взвод',
                'verbose_name_plural': 'Взводи',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name="Ім'я, Прізвище")),
                ('ordinal', models.CharField(max_length=2, verbose_name='Номер в списку')),
                ('external_id', models.PositiveIntegerField(verbose_name='Telegram id')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.journal', verbose_name='Журнал')),
            ],
            options={
                'verbose_name': 'Профіль',
                'verbose_name_plural': 'Взводи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=180)),
                ('date', models.DateField()),
                ('lesson', models.IntegerField(null=True)),
                ('is_present', models.BooleanField(verbose_name='Присутність')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.profile')),
            ],
        ),
    ]
