# Generated by Django 4.1.2 on 2023-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='external_id',
            field=models.IntegerField(verbose_name='Chat id'),
        ),
    ]
