# Generated by Django 4.1.2 on 2023-04-21 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_journal_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.journal', verbose_name='Журнал'),
        ),
    ]
