# Generated by Django 4.1.2 on 2023-04-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_journalentry_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ordinal',
            field=models.CharField(db_index=True, max_length=2, verbose_name='Номер в списку'),
        ),
    ]
