# Generated by Django 4.1.2 on 2023-04-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_profile_ordinal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ordinal',
            field=models.CharField(max_length=2, verbose_name='Номер в списку'),
        ),
    ]
