# Generated by Django 4.1.2 on 2023-04-21 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_profile_ordinal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['ordinal'], 'verbose_name': 'Профіль', 'verbose_name_plural': 'Взводи'},
        ),
    ]
