# Generated by Django 4.1.2 on 2023-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(max_length=60, null=True, verbose_name='Статус'),
        ),
    ]
