# Generated by Django 4.1.2 on 2023-04-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_journalentry_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lessons', models.CharField(max_length=22, null=True)),
                ('table', models.TextField()),
                ('summary', models.TextField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.journal', verbose_name='Журнал')),
            ],
        ),
    ]
