# Generated by Django 4.1.2 on 2023-05-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='table',
            field=models.TextField(null=True),
        ),
    ]
