# Generated by Django 4.1.2 on 2023-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_report_summary_alter_report_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='is_present',
            field=models.BooleanField(null=True, verbose_name='Присутність'),
        ),
    ]
