# Generated by Django 4.1.2 on 2023-05-11 18:53

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_journalentry_is_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lessons',
            field=models.CharField(max_length=15, null=True, verbose_name=django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')),
        ),
    ]
