# Generated by Django 4.1.2 on 2023-05-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_report_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='report',
            name='table',
        ),
    ]
