# Generated by Django 4.1.2 on 2023-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_rename_report_reportparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Superuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='Telegram id')),
            ],
        ),
    ]
