# Generated by Django 4.1.2 on 2023-09-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_alter_journal_strength'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='Telegram id')),
            ],
        ),
    ]
