# Generated by Django 4.1.1 on 2024-03-01 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_presencepoll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['ordinal'], 'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
    ]
