# Generated by Django 4.1.1 on 2024-07-23 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(verbose_name='№ Предмет')),
            ],
            options={
                'verbose_name': 'Заняття',
                'verbose_name_plural': 'Заняття',
            },
        ),
        migrations.RemoveField(
            model_name='reportparameters',
            name='lessons',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Предмет')),
                ('journals', models.ManyToManyField(to='bot.journal')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.ManyToManyField(to='bot.lesson')),
            ],
            options={
                'verbose_name': 'Розклад',
                'verbose_name_plural': 'Розклади',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='CurrentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.journal')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.schedule')),
            ],
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.lesson', verbose_name='Заняття'),
        ),
    ]
